<?php

/**
 * @file
 * Code for OHO Nav module.
 */

/**
 * Implements hook_theme().
 */
function oho_nav_theme($existing, $type, $theme, $path) {
  return [
    'oho_nav' => [
      'variables' => [
        'nav' => NULL,
        'nav_title' => [],
      ],
    ],
  ];
}

/**
 * Implements hook_theme_suggestions_HOOK() for "block".
 */
function oho_nav_theme_suggestions_block(array $variables) {
  $suggestions = [];

  // Check if this is a oho_nav_block block.
  if (isset($variables['elements']['#base_plugin_id']) && $variables['elements']['#base_plugin_id'] == 'oho_menu_block') {
    // Add a base menu block suggestion.
    $suggestions[] = 'block__oho_nav_block';

    // Add a menu block suggestion per region.
    $suggestions[] = 'block__oho_nav_block__region_' . $variables['elements']['#configuration']['region'];
  }

  return $suggestions;
}
