<?php

/**
 * @file
 * Contains functionality for the Louisiana Home module.
 */

/**
 * Implements template_preprocess_node().
 */
function lafayette_home_preprocess_node(&$vars) {
  if ($vars['node']->bundle() == 'home') {
    if ($vars['view_mode'] == 'full') {
      /* Hero */

      // Build the hero.
      $vars['hero'] = [
        '#theme' => 'hero',
        '#hero_type' => 'parallax',
        '#overlay' => TRUE,
        '#video_type' => 'yt_player',
        '#image' => $vars['content']['field_header_image'],
        '#video' => $vars['content']['field_header_video'],
        '#title' => $vars['content']['field_header_title'],
      ];
    }
  }
}
